"""
Quick setup script to create and configure .env file
"""
import os
import secrets

def create_env_file():
    """Create .env file with user input"""
    env_path = os.path.join(os.path.dirname(__file__), '.env')
    
    if os.path.exists(env_path):
        print("⚠️  .env file already exists!")
        response = input("Do you want to overwrite it? (yes/no): ").lower()
        if response != 'yes':
            print("Keeping existing .env file.")
            return
    
    print("\n" + "="*60)
    print("StudyQnA Generator - Environment Setup")
    print("="*60 + "\n")
    
    # Database configuration
    print("📊 DATABASE CONFIGURATION")
    print("-" * 60)
    db_user = input("Database username [studyqna_user]: ").strip() or "studyqna_user"
    db_password = input("Database password: ").strip()
    if not db_password:
        print("❌ Password is required!")
        return
    db_host = input("Database host [localhost]: ").strip() or "localhost"
    db_port = input("Database port [5432]: ").strip() or "5432"
    db_name = input("Database name [studyqna]: ").strip() or "studyqna"
    
    database_url = f"postgresql://{db_user}:{db_password}@{db_host}:{db_port}/{db_name}"
    
    # JWT Secret Key
    print("\n🔐 JWT SECURITY")
    print("-" * 60)
    generate_key = input("Generate new secret key? (yes/no) [yes]: ").strip().lower() or "yes"
    if generate_key == "yes":
        secret_key = secrets.token_urlsafe(32)
        print(f"✅ Generated secret key: {secret_key[:20]}...")
    else:
        secret_key = input("Enter secret key: ").strip()
        if not secret_key:
            secret_key = secrets.token_urlsafe(32)
            print(f"✅ Generated secret key: {secret_key[:20]}...")
    
    # Admin Email
    print("\n👤 ADMIN CONFIGURATION")
    print("-" * 60)
    admin_email = input("Admin email address: ").strip()
    if not admin_email:
        admin_email = "admin@example.com"
        print(f"⚠️  Using default: {admin_email}")
    
    # OpenAI API Key
    print("\n🤖 OPENAI CONFIGURATION")
    print("-" * 60)
    openai_key = input("OpenAI API key (press Enter to skip): ").strip()
    
    # Create .env content
    env_content = f"""# ============================================
# StudyQnA Generator - Environment Configuration
# ============================================
# Generated by setup_env.py
# ============================================

# Database
DATABASE_URL={database_url}

# JWT Security
SECRET_KEY={secret_key}
ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=1440

# Admin
ADMIN_EMAIL={admin_email}

# Storage
STORAGE_PATH=./storage
ENCRYPT_STORAGE=true

# Email Provider - Choose "brevo" (recommended) or "smtp"
EMAIL_PROVIDER=brevo

# Brevo API (Recommended)
# Get API key from: https://app.brevo.com/settings/keys/api
BREVO_API_KEY=
BREVO_FROM_EMAIL=noreply@yourdomain.com
BREVO_FROM_NAME=StudyQnA

# SMTP (Alternative/Backup)
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USER=
SMTP_PASSWORD=
SMTP_FROM=StudyQnA <noreply@studyqna.com>

# OpenAI
OPENAI_API_KEY={openai_key}

# Application
APP_NAME=StudyQnA Generator
APP_URL=http://localhost:3000
"""
    
    # Write .env file
    with open(env_path, 'w') as f:
        f.write(env_content)
    
    print("\n" + "="*60)
    print("✅ .env file created successfully!")
    print("="*60)
    print(f"\n📁 Location: {env_path}")
    print("\n📝 Next steps:")
    print("   1. Review the .env file if needed")
    print("   2. Run: python init_db.py")
    print("   3. Start server: python run.py")
    print()

if __name__ == "__main__":
    try:
        create_env_file()
    except KeyboardInterrupt:
        print("\n\n❌ Setup cancelled.")
    except Exception as e:
        print(f"\n❌ Error: {e}")

